In [9]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [16]:
import pandas as pd
from IPython.display import display

cols = ['Metryka', 'Mean', 'Std']

xgb = catalog.load("cv_results_xgboost_kbest")[cols]
rf = catalog.load("cv_results_rf_kbest")[cols]
lr = catalog.load("cv_results_lr_kbest")[cols]

print("XGBoost:")
display(xgb)

print("\nRandom Forest:")
display(rf)

print("\nLinear Regression:")
display(lr)

[03/27/26 12:43:56] INFO     Loading data from cv_results_xgboost_kbest (CSVDataset)...        ]8;id=947671;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=918517;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_kbest (CSVDataset)...             ]8;id=420609;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=926668;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_kbest (CSVDataset)...             ]8;id=608209;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=549843;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

XGBoost:

  Metryka       Mean       Std
0    rmse  30930.323  5265.997
1      r2      0.837     0.043
2    mape     10.705     0.476

Random Forest:

  Metryka       Mean       Std
0    rmse  29470.935  4724.845
1      r2      0.852     0.036
2    mape     10.326     0.484

Linear Regression:

  Metryka       Mean       Std
0    rmse  34565.575  6196.812
1      r2      0.796     0.059
2    mape     12.827     0.553

In [11]:
import pandas as pd
from IPython.display import display

cols = ['Metryka', 'Mean', 'Std']

def merge_results(simple, cat, num, full, target_ohe):
    s = simple.rename(columns={'Mean': 'Simple_Mean', 'Std': 'Simple_Std'})
    c = cat.rename(columns={'Mean': 'Cat_Mean', 'Std': 'Cat_Std'})
    n = num.rename(columns={'Mean': 'Num_Mean', 'Std': 'Num_Std'})
    f = full.rename(columns={'Mean': 'Full_Mean', 'Std': 'Full_Std'})
    t = target_ohe.rename(columns={'Mean': 'TargetOHE_Mean', 'Std': 'TargetOHE_Std'})
    
    merged = s.merge(c, on='Metryka').merge(n, on='Metryka').merge(f, on='Metryka').merge(t, on='Metryka')
    
    cols_order = [
        'Metryka', 
        'Simple_Mean', 'Cat_Mean', 'Num_Mean', 'Full_Mean', 'TargetOHE_Mean',
        'Simple_Std', 'Cat_Std', 'Num_Std', 'Full_Std', 'TargetOHE_Std'
    ]
    
    return merged[cols_order]

xgb_simple = catalog.load("cv_results_xgboost_simple")[cols]
xgb_cat = catalog.load("cv_results_xgboost_categories")[cols]
xgb_num = catalog.load("cv_results_xgboost_numerical")[cols]
xgb_full = catalog.load("cv_results_xgboost_full")[cols]
xgb_target_ohe = catalog.load("cv_results_xgboost_target_ohe")[cols]

rf_simple = catalog.load("cv_results_rf_simple")[cols]
rf_cat = catalog.load("cv_results_rf_categories")[cols]
rf_num = catalog.load("cv_results_rf_numerical")[cols]
rf_full = catalog.load("cv_results_rf_full")[cols]
rf_target_ohe = catalog.load("cv_results_rf_target_ohe")[cols]

lr_simple = catalog.load("cv_results_lr_simple")[cols]
lr_cat = catalog.load("cv_results_lr_categories")[cols]
lr_num = catalog.load("cv_results_lr_numerical")[cols]
lr_full = catalog.load("cv_results_lr_full")[cols]
lr_target_ohe = catalog.load("cv_results_lr_target_ohe")[cols]

print("XGBoost:")
display(merge_results(xgb_simple, xgb_cat, xgb_num, xgb_full, xgb_target_ohe))

print("\nRandom Forest:")
display(merge_results(rf_simple, rf_cat, rf_num, rf_full, rf_target_ohe))

print("\nLinear Regression:")
display(merge_results(lr_simple, lr_cat, lr_num, lr_full, lr_target_ohe))

[03/27/26 11:41:45] INFO     Loading data from cv_results_xgboost_simple (CSVDataset)...       ]8;id=80899;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=799941;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_xgboost_categories (CSVDataset)...   ]8;id=236368;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=425744;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_xgboost_numerical (CSVDataset)...    ]8;id=117417;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=380126;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_xgboost_full (CSVDataset)...         ]8;id=565062;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=985782;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_xgboost_target_ohe (CSVDataset)...   ]8;id=259522;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=503606;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_simple (CSVDataset)...            ]8;id=394199;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=922727;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_categories (CSVDataset)...        ]8;id=637532;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=824632;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_numerical (CSVDataset)...         ]8;id=299059;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=472146;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_full (CSVDataset)...              ]8;id=947775;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=723178;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_rf_target_ohe (CSVDataset)...        ]8;id=132062;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=565468;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_simple (CSVDataset)...            ]8;id=659267;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=823855;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_categories (CSVDataset)...        ]8;id=165915;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=236928;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_numerical (CSVDataset)...         ]8;id=267792;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=476971;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_full (CSVDataset)...              ]8;id=385268;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=614949;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from cv_results_lr_target_ohe (CSVDataset)...        ]8;id=832782;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=369427;file://C:\Users\arczi\source\repos\Mini\Msi\wsi-reg-cls\wsi-reg\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

XGBoost:

,Metryka,Simple_Mean,Cat_Mean,Num_Mean,Full_Mean,TargetOHE_Mean,Simple_Std,Cat_Std,Num_Std,Full_Std,TargetOHE_Std
0,rmse,31348.022,30471.969,30822.167,29881.344,30413.947,5721.348,5853.752,4662.371,5526.752,5196.378
1,r2,0.832,0.841,0.838,0.848,0.842,0.051,0.049,0.040,0.046,0.044
2,mape,10.501,10.358,10.534,10.204,10.478,0.651,0.628,0.520,0.594,0.578

Random Forest:

,Metryka,Simple_Mean,Cat_Mean,Num_Mean,Full_Mean,TargetOHE_Mean,Simple_Std,Cat_Std,Num_Std,Full_Std,TargetOHE_Std
0,rmse,30638.387,29707.007,30762.213,29479.553,29823.157,5111.653,4958.430,5458.966,4755.580,4825.979
1,r2,0.840,0.850,0.839,0.852,0.849,0.042,0.039,0.045,0.036,0.037
2,mape,10.578,10.290,10.592,10.246,10.421,0.566,0.549,0.571,0.501,0.513

Linear Regression:

,Metryka,Simple_Mean,Cat_Mean,Num_Mean,Full_Mean,TargetOHE_Mean,Simple_Std,Cat_Std,Num_Std,Full_Std,TargetOHE_Std
0,rmse,33902.606,33695.948,33066.338,33395.753,33884.369,7410.061,5949.280,5822.643,5825.278,7331.820
1,r2,0.802,0.807,0.814,0.810,0.802,0.075,0.055,0.053,0.053,0.074
2,mape,11.461,12.450,11.753,12.343,11.586,0.693,0.589,0.925,0.601,0.486